# Generated by Django 5.0.6 on 2024-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
