# Generated by Django 5.0.6 on 2024-08-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_home_correo_alter_home_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Usuario',
        ),
    ]
